### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by max1mka1**
## Description

Fixes # (issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I wrote unit tests for my code _(if tests is required for my changes)_
- [ ] I have made changes in `CHANGELOG.md` file

### CODE REVIEW

**Comment by max1mka1** [comment]
1

**Comment by max1mka1** [comment]
2

**Comment by max1mka1** [comment]
2

**Comment by tarampampam** [comment]
Please, do NOT make a PR - send link to your repository with your decision to the teamlead or HR instead.

**Pull request closed without merging**
